.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tomat-daemon-run 1  "run " 
.SH NAME
tomat-daemon-run \- Run the daemon in the foreground (internal use)
.SH SYNOPSIS
\fBtomat daemon run\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Run the daemon in the foreground (internal use)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
