.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tomat-pause 1  "pause " 
.SH NAME
pause \- Pause the current timer
.SH SYNOPSIS
\fBpause\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Pause the currently running timer. Use \*(Aqresume\*(Aq or \*(Aqtoggle\*(Aq to continue.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
