.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tomat-toggle 1  "toggle " 
.SH NAME
toggle \- Toggle timer pause/resume
.SH SYNOPSIS
\fBtoggle\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Toggle the timer state: pause if running, resume if paused. This is useful for waybar click handlers.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
