.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tomat-daemon-status 1  "status " 
.SH NAME
tomat-daemon-status \- Check daemon status
.SH SYNOPSIS
\fBtomat daemon status\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Check if the tomat daemon is currently running and report its process ID.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
