.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tomat-stop 1  "stop " 
.SH NAME
stop \- Stop the current session
.SH SYNOPSIS
\fBstop\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Stop the current Pomodoro session and return the timer to idle state.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
