.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tomat-resume 1  "resume " 
.SH NAME
resume \- Resume a paused timer
.SH SYNOPSIS
\fBresume\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Resume a paused timer from where it left off.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
