.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tomat-daemon-uninstall 1  "uninstall " 
.SH NAME
tomat-daemon-uninstall \- Uninstall systemd user service
.SH SYNOPSIS
\fBtomat daemon uninstall\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Stop and remove the tomat systemd user service. This removes the service file and disables automatic startup.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
